import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header/Header";
import NavBar from "@/components/NavBar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="flex flex-col justify-center w-full h-full">
          <Header />
          <section className="w-full h-max flex justify-center items-center">
            <NavBar />
            <section className="w-4/5">{children}</section>
          </section>
        </section>
      </body>
    </html>
  );
}
