import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header/Header";
import NavBar from "@/components/NavBar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Translate Free",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-screen">
      <body className={`${inter.className} h-full w-full`}>
        <section className="flex flex-col justify-center w-full h-full">
          <Header />
          <section className="relative w-full h-full flex justify-center items-center">
            <NavBar />
            <section className="w-[83%]">{children}</section>
          </section>
        </section>
      </body>
    </html>
  );
}
